---
language: python
os: linux
jobs:
  include:
    - language: python
      python: 3.6
      before_install:
        - pip install wheel
      cache: pip
      install:
        - pip install -r requirements.txt
        - pip install -r test-requirements.txt
      script:
        - tool/run-python-tests
    - language: node_js
      node_js:
        - '10'
      cache:
        yarn: true
        directories:
          - '.eslintcache'
          - 'node_modules'
      install: yarn --no-progress --frozen-lockfile --ignore-engines
      script:
        - tool/run-javascript-tests
