# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-07 19:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20150705_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogauthor',
            name='author',
        ),
        migrations.AlterField(
            model_name='article',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='article',
            name='modified_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='articlecomment',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='articlecomment',
            name='modified_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='articlecomment',
            name='poster_name',
            field=models.CharField(blank=True, default='Anonymous', max_length=255, verbose_name='Name'),
        ),
        migrations.DeleteModel(
            name='BlogAuthor',
        ),
    ]
