# Generated by Django 2.2.1 on 2019-05-11 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_commenters_without_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='commenter',
            name='ip_hash',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
