# Generated by Django 2.2.1 on 2019-05-11 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_create_ip_hashes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commenter',
            name='ip_address',
        ),
        migrations.AlterField(
            model_name='commenter',
            name='ip_hash',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
