#!/usr/bin/env bash

# A script for running all Python tests.

function join { local IFS="$1"; shift; echo "$*"; }

module_list=(
    w0rplib
    blog
    misc
)

# Build comma separated values for the coverage report.
csv=$(join , "${module_list[@]}")
# Find all empty __init__.py files so we can exclude them.
# shellcheck disable=SC2046
empty_init_csv=$(join , $(find . -type f -empty -name __init__.py))

if [ -f env/bin/activate ]; then
    # shellcheck disable=SC1091
    source env/bin/activate
fi

# Tests can fail if we don't collect static files first.
python manage.py collectstatic --settings=settings_test --noinput > /dev/null
export PYTHONWARNINGS=always
coverage run --branch --omit "*/migrations/*,$empty_init_csv" \
    --source="$csv" \
    manage.py test --settings=settings_test --noinput "${module_list[@]}"
